<a href="https://colab.research.google.com/github/biswajit-github-2022/RKMVERI_2ND/blob/main/Deep_Learning/hands_on_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New section

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
x=tf.constant(4, shape=(1,1), dtype=tf.float32)
x=tf.constant([[1,2,3],[1,2,3]])
# print(y)
x=tf.ones((2,3))
x=tf.zeros((2,3))
x=tf.eye((2))

# dist
x=tf.random.normal((3,3),mean=0,stddev=1)
x=tf.random.uniform((3,3),minval=0,maxval=1)
x=tf.range(start=1,limit=10,delta=2)
x=tf.cast(x,tf.float16)


# math
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
# z=x+y
z=tf.add(x,y)
z=tf.subtract(x,y)
z=tf.divide(x,y)
z=tf.multiply(x,y)
z=tf.tensordot(x,y,axes=0)#3*3
z=tf.tensordot(x,y,axes=1)#same
z=tf.reduce_sum(x*y,axis=0)#same
z**=5
print(z)
print(x)

tf.Tensor(205962976, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:


x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
z=x@y
print(z)


# indexing
x=tf.constant([0,1,2,3,1,2,3])
# print(x[0])
# print(x[:])
# print(x[1:])
# print(x[1:3])
# print(x[::2])
# print(x[::-1])
# want index 0,2
indices=tf.constant([0,6])
x_index=tf.gather(x,indices)
print(x_index)

# matrix index
x=tf.constant([[1,2],[3,4],[5,6]])
print(x[1:2,0:1])#-->3
print(x[1:,:1])

# reshaping
x=tf.range(9)
x=tf.reshape(x,(3,3))
print(x)
y=tf.transpose(x,perm=[1,0])
print(y)

tf.Tensor(
[[-2.5806358   0.46112704  2.820477    1.7840967 ]
 [-1.6166298   0.4712274   1.6844383   0.63475925]], shape=(2, 4), dtype=float32)
tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor([[3]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[3]
 [5]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


# Basic NN

In [7]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
# print(mnist)

(x_train,y_train),(x_test,y_test)=mnist.load_data()
# print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)
x_train=x_train.reshape(-1,28*28).astype("float32")/255.0
x_test=x_test.reshape(-1,28*28).astype("float32")/255.0
# print(x_train.shape)

# sequensial API(convinent but not flexible)
# model=keras.Sequential(
#     [
#         keras.Input(shape=(28*28)),
#         layers.Dense(512,activation='relu'),
#         layers.Dense(256,activation='relu'),
#         layers.Dense(10),
#     ]
# )

# another way to add layers to model using Squensial API
# model=keras.Sequential()
# model.add(layers.Dense(512,activation='relu'))
# model.add(layers.Dense(256,activation='relu'))
# model.add(layers.Dense(10))


# Functional API
inputs=keras.Input(shape=(28*28))
x=layers.Dense(512,activation='relu',name='Fist_layer')(inputs)
x=layers.Dense(256,activation='relu',name='Second_layer')(x)
outputs=layers.Dense(10,activation='softmax',name='Third_layer')(x)
model=keras.Model(inputs=inputs,outputs=outputs)
# model=keras.Model(inputs=model.inputs,
#                   outputs=[model.layers[-2].output])
model=keras.Model(inputs=model.inputs,
                  outputs=[layer.output for layer in model.layers]) ##for all layers
# model=keras.Model(inputs=model.inputs,
#                   outputs=[model.get_layer('Third_layer').output])
features=model.predict(x_train)
for feature in features:
  print(feature.shape)


print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

1875/1875 [==============================] - 2s 872us/step
(60000, 784)
(60000, 512)
(60000, 256)
(60000, 10)
Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 784)]             0         
                                                                 
 Fist_layer (Dense)          (None, 512)               401920    
                                                                 
 Second_layer (Dense)        (None, 256)               131328    
                                                                 
 Third_layer (Dense)         (None, 10)                2570      
                                                                 
Total params: 535818 (2.04 MB)
Trainable params: 535818 (2.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


None
Epoch 1/5


/home/biswajitrana/.local/lib/python3.10/site-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 - 9s - loss: 8.1060 - input_1_loss: 6.8522 - Fist_layer_loss: 0.6598 - Second_layer_loss: 0.3830 - Third_layer_loss: 0.2110 - input_1_accuracy: 0.0000e+00 - Fist_layer_accuracy: 0.8609 - Second_layer_accuracy: 0.9144 - Third_layer_accuracy: 0.9364 - 9s/epoch - 5ms/step
Epoch 2/5
1875/1875 - 8s - loss: 7.3388 - input_1_loss: 6.8521 - Fist_layer_loss: 0.3135 - Second_layer_loss: 0.0838 - Third_layer_loss: 0.0894 - input_1_accuracy: 0.0000e+00 - Fist_layer_accuracy: 0.9144 - Second_layer_accuracy: 0.9751 - Third_layer_accuracy: 0.9724 - 8s/epoch - 4ms/step
Epoch 3/5
1875/1875 - 8s - loss: 7.2560 - input_1_loss: 6.8521 - Fist_layer_loss: 0.2888 - Second_layer_loss: 0.0549 - Third_layer_loss: 0.0602 - input_1_accuracy: 0.0000e+00 - Fist_layer_accuracy: 0.9209 - Second_layer_accuracy: 0.9837 - Third_layer_accuracy: 0.9809 - 8s/epoch - 4ms/step
Epoch 4/5
1875/1875 - 8s - loss: 7.2156 - input_1_loss: 6.8521 - Fist_layer_loss: 0.2776 - Second_layer_loss: 0.0398 - Third_layer_loss: 0.0

[7.291595935821533,
 6.854820251464844,
 0.26830387115478516,
 0.07446655631065369,
 0.09400609880685806,
 0.0,
 0.9266999959945679,
 0.9799000024795532,
 0.9775999784469604]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')