<a href="https://colab.research.google.com/github/biswajit-github-2022/RKMVERI_2ND/blob/main/Deep_Learning/hands_on_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New section

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [52]:
x=tf.constant(4, shape=(1,1), dtype=tf.float32)
x=tf.constant([[1,2,3],[1,2,3]])
# print(y)
x=tf.ones((2,3))
x=tf.zeros((2,3))
x=tf.eye((2))

# dist
x=tf.random.normal((3,3),mean=0,stddev=1)
x=tf.random.uniform((3,3),minval=0,maxval=1)
x=tf.range(start=1,limit=10,delta=2)
x=tf.cast(x,tf.float16)


# math
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
# z=x+y
z=tf.add(x,y)
z=tf.subtract(x,y)
z=tf.divide(x,y)
z=tf.multiply(x,y)
z=tf.tensordot(x,y,axes=0)#3*3
z=tf.tensordot(x,y,axes=1)#same
z=tf.reduce_sum(x*y,axis=0)#same
z**=5
print(z)
print(x)

tf.Tensor(205962976, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [78]:


x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
z=x@y
print(z)


# indexing
x=tf.constant([0,1,2,3,1,2,3])
# print(x[0])
# print(x[:])
# print(x[1:])
# print(x[1:3])
# print(x[::2])
# print(x[::-1])
# want index 0,2
indices=tf.constant([0,6])
x_index=tf.gather(x,indices)
print(x_index)

# matrix index
x=tf.constant([[1,2],[3,4],[5,6]])
print(x[1:2,0:1])#-->3
print(x[1:,:1])

# reshaping
x=tf.range(9)
x=tf.reshape(x,(3,3))
print(x)
y=tf.transpose(x,perm=[1,0])
print(y)

tf.Tensor(
[[ 0.89116335 -1.1899775  -1.9823257  -1.2180679 ]
 [-0.9232565   1.4684417   2.3125591   0.11903507]], shape=(2, 4), dtype=float32)
tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor([[3]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[3]
 [5]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


# Basic NN

In [96]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
# print(mnist)

(x_train,y_train),(x_test,y_test)=mnist.load_data()
# print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)
x_train=x_train.reshape(-1,28*28).astype("float32")/255.0
x_test=x_test.reshape(-1,28*28).astype("float32")/255.0
# print(x_train.shape)

# sequensial API(convinent but not flexible)
# model=keras.Sequential(
#     [
#         keras.Input(shape=(28*28)),
#         layers.Dense(512,activation='relu'),
#         layers.Dense(256,activation='relu'),
#         layers.Dense(10),
#     ]
# )

# another way to add layers to model using Squensial API
# model=keras.Sequential()
# model.add(layers.Dense(512,activation='relu'))
# model.add(layers.Dense(256,activation='relu'))
# model.add(layers.Dense(10))


# Functional API
inputs=keras.Input(shape=(28*28))
x=layers.Dense(512,activation='relu',name='Fist_layer')(inputs)
x=layers.Dense(256,activation='relu',name='Second_layer')(x)
outputs=layers.Dense(10,activation='softmax',name='Third_layer')(x)
model=keras.Model(inputs=inputs,outputs=outputs)
# model=keras.Model(inputs=model.inputs,
#                   outputs=[model.layers[-2].output])
model=keras.Model(inputs=model.inputs,
                  outputs=[layer.output for layer in model.layers]) ##for all layers
# model=keras.Model(inputs=model.inputs,
#                   outputs=[model.get_layer('Third_layer').output])
features=model.predict(x_train)
for feature in features:
  print(feature.shape)


print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

1875/1875 [==============================] - 3s 2ms/step
(60000, 784)
(60000, 512)
(60000, 256)
(60000, 10)
Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 784)]             0         
                                                                 
 Fist_layer (Dense)          (None, 512)               401920    
                                                                 
 Second_layer (Dense)        (None, 256)               131328    
                                                                 
 Third_layer (Dense)         (None, 10)                2570      
                                                                 
Total params: 535818 (2.04 MB)
Trainable params: 535818 (2.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


None
Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 - 6s - loss: 8.6819 - input_5_loss: 6.8522 - Fist_layer_loss: 1.3824 - Second_layer_loss: 0.2401 - Third_layer_loss: 0.2072 - input_5_accuracy: 0.0000e+00 - Fist_layer_accuracy: 0.7603 - Second_layer_accuracy: 0.9379 - Third_layer_accuracy: 0.9373 - 6s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 5s - loss: 7.5418 - input_5_loss: 6.8522 - Fist_layer_loss: 0.5172 - Second_layer_loss: 0.0835 - Third_layer_loss: 0.0889 - input_5_accuracy: 0.0000e+00 - Fist_layer_accuracy: 0.8856 - Second_layer_accuracy: 0.9752 - Third_layer_accuracy: 0.9722 - 5s/epoch - 3ms/step
Epoch 3/5
1875/1875 - 5s - loss: 7.2621 - input_5_loss: 6.8522 - Fist_layer_loss: 0.2921 - Second_layer_loss: 0.0553 - Third_layer_loss: 0.0625 - input_5_accuracy: 0.0000e+00 - Fist_layer_accuracy: 0.9202 - Second_layer_accuracy: 0.9832 - Third_layer_accuracy: 0.9806 - 5s/epoch - 3ms/step
Epoch 4/5
1875/1875 - 5s - loss: 7.2148 - input_5_loss: 6.8521 - Fist_layer_loss: 0.2788 - Second_layer_loss: 0.0381 - Third_layer_loss: 0.0

[7.2640533447265625,
 6.854820251464844,
 0.2700355648994446,
 0.06740257889032364,
 0.07179230451583862,
 0.0,
 0.9259999990463257,
 0.978600025177002,
 0.9785000085830688]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')