<a href="https://colab.research.google.com/github/biswajit-github-2022/RKMVERI_2ND/blob/main/Deep_Learning/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
tf.abs(2-3)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
x=tf.constant([[1,2,3],[2,3,4]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>