In [182]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [183]:
df =pd.read_csv("annotated_points_np_200.csv")

In [184]:
data=np.array(df)

### Changing labels

In [185]:
data[data == 2.0] = -1

In [186]:
data

array([[ 1.51209677,  3.58766234,  1.        ],
       [ 4.41532258,  6.42857143,  1.        ],
       [ 2.78225806,  6.59090909,  1.        ],
       [ 1.875     ,  8.37662338,  1.        ],
       [ 2.96370968, 10.73051948,  1.        ],
       [ 3.75      , 11.86688312,  1.        ],
       [ 5.2016129 , 12.43506494,  1.        ],
       [ 7.25806452, 12.02922078,  1.        ],
       [ 7.68145161, 11.2987013 ,  1.        ],
       [ 7.5       , 10.40584416,  1.        ],
       [ 6.89516129,  9.91883117,  1.        ],
       [ 6.29032258, 10.        ,  1.        ],
       [ 5.80645161, 12.43506494,  1.        ],
       [ 5.74596774, 15.60064935,  1.        ],
       [ 6.16935484, 16.08766234,  1.        ],
       [ 7.86290323, 15.27597403,  1.        ],
       [ 9.25403226, 13.40909091,  1.        ],
       [ 9.01209677, 11.21753247,  1.        ],
       [ 7.0766129 ,  8.7012987 ,  1.        ],
       [ 5.26209677,  7.24025974,  1.        ],
       [ 5.08064516,  7.15909091,  1.   

### Data and Label division

In [187]:
coord_data=data[:,0:2]
y=data[:,2]

In [188]:
coord_data.shape

(200, 2)

In [189]:
y.shape

(200,)

In [190]:
one=np.ones(coord_data.shape[0]).reshape(200,1)
X=np.concatenate([coord_data,one],axis=1)

### Algorithm implementation

In [191]:
print(y.shape)
print(coord_data.shape)
print(data.shape)

(200,)
(200, 2)
(200, 3)


In [201]:
W=np.array([0,0,0])

In [202]:
W

array([0, 0, 0])

In [203]:
W.T

array([0, 0, 0])

In [194]:
while (1):
    m=0
    for i in range(X.shape[0]):
        if(y[i]*np.dot(W.T,X[i])<=0):
            W=W+y[i]*X[i]
            m=m+1
    if(m==0):
        break

ValueError: shapes (1,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)