In [2]:
import numpy as np
import pandas as pd

In [3]:
df =pd.read_csv("annotated_points_np_100.csv")

In [4]:
data=np.array(df)

### Changing labels

In [5]:
data[data == 2.0] = -1

In [6]:
data

array([[ 3.87096774,  6.59090909,  1.        ],
       [ 4.65725806,  5.69805195,  1.        ],
       [ 4.41532258,  8.78246753,  1.        ],
       [ 3.08467742,  7.72727273,  1.        ],
       [ 2.35887097,  8.45779221,  1.        ],
       [ 2.60080645, 10.08116883,  1.        ],
       [ 3.99193548,  8.62012987,  1.        ],
       [ 5.2016129 ,  6.75324675,  1.        ],
       [ 5.625     ,  5.29220779,  1.        ],
       [ 5.56451613,  3.26298701,  1.        ],
       [ 3.99193548,  3.18181818,  1.        ],
       [ 2.96370968,  5.21103896,  1.        ],
       [ 2.2983871 ,  7.24025974,  1.        ],
       [ 3.20564516,  8.86363636,  1.        ],
       [ 5.56451613,  9.26948052,  1.        ],
       [ 6.65322581,  7.80844156,  1.        ],
       [ 7.43951613,  5.37337662,  1.        ],
       [ 7.25806452,  3.34415584,  1.        ],
       [ 6.83467742,  3.26298701,  1.        ],
       [ 6.53225806,  6.50974026,  1.        ],
       [ 5.26209677,  9.67532468,  1.   

### Data and Label division

In [7]:
coord_data=data[:,0:2]
y=data[:,2]

In [8]:
coord_data.shape

(100, 2)

In [9]:
y.shape

(100,)

In [10]:
one=np.ones(coord_data.shape[0]).reshape(100,1)
X=np.concatenate([coord_data,one],axis=1)

### Algorithm implementation

In [17]:
W=np.array([2,-1,1]).reshape((3,1))

In [25]:
W

array([[ 2],
       [-1],
       [ 1]])

In [23]:
W_old=W
W_new=np.array([0,0,0]).reshape(3,1)
for i in range(coord_data.shape[0]):
    if y[i]*np.dot(W.T,X[i])<=0 :
        W_new = W_old + y[i] *X[i]
    if np.abs(np.sum(W_new-W_old))<0.01:
        break
print(W_old)
print(W_new)

[[ 2]
 [-1]
 [ 1]]
[[-23.88709677 -23.17857143   1.        ]
 [-26.88709677 -26.17857143  -2.        ]
 [-24.88709677 -24.17857143   0.        ]]
