In [1]:
import pandas as pd
import numpy as np
# from matplotlib import pyplot as plt
# %matplotlib inline

In [127]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [103]:
data=pd.read_csv("Real_estate.csv")
data

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [104]:
data.isna().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [105]:
data =data.drop(data.columns[[0,-3,-2]],axis=1)
data_numpy=data.to_numpy()
data_numpy

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   37.9    ],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   42.2    ],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   47.3    ],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   40.6    ],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   52.5    ],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   63.9    ]])

In [106]:

data_numpy[:,-1][:,np.newaxis].min()


7.6

In [107]:
train,test=80,20
train_len=int(len(data_numpy)*(80/100))
test_len=int(len(data_numpy)*(20/100))
test_len+train_len

413

In [108]:
X_train=data_numpy[:train_len,0:data_numpy.shape[1]-1]
y_train=data_numpy[:train_len,-1][:,np.newaxis]
X_test=data_numpy[train_len:test_len+train_len,0:data_numpy.shape[1]-1]
y_test=data_numpy[train_len:test_len+train_len,-1][:,np.newaxis]
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)
# print(X_train,X_test,y_train,y_test)


(331, 4) (82, 4) (331, 1) (82, 1)


In [109]:
reg = LinearRegression().fit(X_train, y_train)

In [110]:
reg.score(X_train, y_train)

0.5444236969933561

In [111]:
reg.coef_

array([[ 5.87019021e+00, -2.75450590e-01, -5.36476972e-03,
         1.32135706e+00]])

In [112]:
prediction=reg.predict(X_test)

In [113]:
prediction

array([[13.00600241],
       [31.69607251],
       [44.77830135],
       [34.76956095],
       [44.36936756],
       [32.59017953],
       [36.13124264],
       [43.693046  ],
       [48.67291461],
       [33.59623398],
       [37.38776173],
       [50.23195617],
       [40.67122552],
       [19.20313833],
       [39.4002998 ],
       [34.6166196 ],
       [ 7.4939593 ],
       [46.63758827],
       [44.77830135],
       [42.67999019],
       [32.53529494],
       [25.91476902],
       [36.59950137],
       [35.4617569 ],
       [47.31814748],
       [38.71938839],
       [54.87145839],
       [49.91679247],
       [30.81873933],
       [44.07797681],
       [40.49568804],
       [40.18307449],
       [49.01163963],
       [41.02910672],
       [30.25070557],
       [28.62740267],
       [30.07198334],
       [39.22364839],
       [27.07234764],
       [41.55727269],
       [49.08377664],
       [41.41606908],
       [42.68841894],
       [46.84145039],
       [31.62779103],
       [34

In [114]:
# Assuming y_test and y_pred are your true labels and predictions, respectively
mse = mean_squared_error(y_test, prediction)
mse

59.507402290756936

In [115]:
predictions = reg.predict(np.array([[2013.500,8.5,104.8101,5]]))
predictions

array([[48.98812859]])

In [126]:
np.sum(((y_test-prediction)**2))/y_test.shape[0]

59.507402290756936

In [129]:


# Assuming y_true and y_pred are your true labels and predictions, respectively
r2 = r2_score(y_test, prediction)
print("R-squared (R2) score:", r2)

R-squared (R2) score: 0.5922103030826429
